//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maestro.Core.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maestro.Core.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Resource ID to clipboard.
        /// </summary>
        public static string Cmd_CopyResourceId {
            get {
                return ResourceManager.GetString("Cmd_CopyResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Package.
        /// </summary>
        public static string Cmd_CreatePackage {
            get {
                return ResourceManager.GetString("Cmd_CreatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Cmd_Exit {
            get {
                return ResourceManager.GetString("Cmd_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Source Preview.
        /// </summary>
        public static string Cmd_FsPreview {
            get {
                return ResourceManager.GetString("Cmd_FsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Package.
        /// </summary>
        public static string Cmd_LoadPackage {
            get {
                return ResourceManager.GetString("Cmd_LoadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Resource.
        /// </summary>
        public static string Cmd_NewResource {
            get {
                return ResourceManager.GetString("Cmd_NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Editor.
        /// </summary>
        public static string Cmd_PackageEditor {
            get {
                return ResourceManager.GetString("Cmd_PackageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string Cmd_SaveAll {
            get {
                return ResourceManager.GetString("Cmd_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Resource.
        /// </summary>
        public static string Cmd_SaveResource {
            get {
                return ResourceManager.GetString("Cmd_SaveResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Resource As.
        /// </summary>
        public static string Cmd_SaveResourceAs {
            get {
                return ResourceManager.GetString("Cmd_SaveResourceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status Monitor.
        /// </summary>
        public static string Cmd_ServerMon {
            get {
                return ResourceManager.GetString("Cmd_ServerMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Welcome Tab.
        /// </summary>
        public static string Cmd_ShowWelcomeTab {
            get {
                return ResourceManager.GetString("Cmd_ShowWelcomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administrator.
        /// </summary>
        public static string Cmd_SiteAdmin {
            get {
                return ResourceManager.GetString("Cmd_SiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Common_About {
            get {
                return ResourceManager.GetString("Common_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Common_Cut {
            get {
                return ResourceManager.GetString("Common_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Common_Help {
            get {
                return ResourceManager.GetString("Common_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Common_Options {
            get {
                return ResourceManager.GetString("Common_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Common_Paste {
            get {
                return ResourceManager.GetString("Common_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect_Connect {
            get {
                return ResourceManager.GetString("Connect_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Connect_Password {
            get {
                return ResourceManager.GetString("Connect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Connect_Site {
            get {
                return ResourceManager.GetString("Connect_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Connect_Username {
            get {
                return ResourceManager.GetString("Connect_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Package.
        /// </summary>
        public static string Menu_Tools_Package {
            get {
                return ResourceManager.GetString("Menu_Tools_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Site.
        /// </summary>
        public static string SiteExplorer_Connect {
            get {
                return ResourceManager.GetString("SiteExplorer_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to any site.
        /// </summary>
        public static string SiteExplorer_NotConnectedWarning {
            get {
                return ResourceManager.GetString("SiteExplorer_NotConnectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Explorer.
        /// </summary>
        public static string SiteExplorer_Title {
            get {
                return ResourceManager.GetString("SiteExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this folder.
        /// </summary>
        public static string SiteExplorer_Tooltip_OpenFolder {
            get {
                return ResourceManager.GetString("SiteExplorer_Tooltip_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this resource.
        /// </summary>
        public static string SiteExplorer_Tooltip_OpenResource {
            get {
                return ResourceManager.GetString("SiteExplorer_Tooltip_OpenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string Stat_NotConnected {
            get {
                return ResourceManager.GetString("Stat_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Other Text.
        /// </summary>
        public static string Stat_SomeOtherText {
            get {
                return ResourceManager.GetString("Stat_SomeOtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authoring tool for MapGuide Open Source / AIMS.
        /// </summary>
        public static string Welcome_AppDesc {
            get {
                return ResourceManager.GetString("Welcome_AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website.
        /// </summary>
        public static string Welcome_ProjectWebsite {
            get {
                return ResourceManager.GetString("Welcome_ProjectWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Welcome_Start {
            get {
                return ResourceManager.GetString("Welcome_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome_TabTitle {
            get {
                return ResourceManager.GetString("Welcome_TabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Resources.
        /// </summary>
        public static string Welcome_UsefulResources {
            get {
                return ResourceManager.GetString("Welcome_UsefulResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string Welcome_UserGuide {
            get {
                return ResourceManager.GetString("Welcome_UserGuide", resourceCulture);
            }
        }
    }
}
