# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add wasm workload
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish windows
      run: dotnet publish -c Release -r win-x64 --self-contained -o publish/desktop/win-x64 ./src/Maestro.Desktop
    - name: Publish windows single file
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true --self-contained -o publish/desktop-sf/win-x64 ./src/Maestro.Desktop
    - name: Publish linux
      run: dotnet publish -c Release -r linux-x64 --self-contained -o publish/desktop/linux-x64 ./src/Maestro.Desktop
    - name: Publish WASM AppBundle
      run: |
        dotnet publish -c Release -r browser-wasm ./src/Maestro.Browser
        mkdir -p ./publish
        cp -R ./src/Maestro.Browser/bin/Release/net8.0/browser-wasm/AppBundle ./publish/browser-wasm
    - name: Deploy WASM AppBundle to GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/browser-wasm
