# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add libfuse
      run: sudo apt-get install libfuse2
    - name: Add wasm workload
      run: dotnet workload install wasm-tools
    - name: Add pupnet
      run: dotnet tool install -g KuiperZone.PupNet
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish windows
      run: pupnet --runtime win-x64 --kind zip
    #- name: Publish windows single file
    #  run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true --self-contained -o publish/desktop-sf/win-x64 ./src/Maestro.Desktop
    - name: Publish linux
      run: pupnet --runtime linux-x64 --kind zip --skip-yes
    - name: Publish osx
      run: pupnet --runtime osx-x64 --kind zip --skip-yes
    - name: Publish WASM AppBundle
      run: |
        dotnet publish -c Release -r browser-wasm ./src/Maestro.Browser
        mkdir -p ./artifacts
        cp -R ./src/Maestro.Browser/bin/Release/net8.0/browser-wasm/AppBundle ./artifacts/browser-wasm
        tar -zcf ./artifacts/files/mapguide-maestro-wasm-appbundle.tar.gz -C ./artifacts/browser-wasm .
    - name: Publish linux appimage
      run: pupnet --runtime linux-x64 --kind appimage --skip-yes
    - name: Deploy WASM AppBundle to GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: ${{ github.ref_name }}
        publish_dir: ./artifacts/browser-wasm
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: artifacts/files/*
